apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: bookstack-secret
          env:
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bookstack-secret
                  key: DB_DATABASE
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: bookstack-secret
                  key: DB_USERNAME
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstack-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: bookstack
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP