apiVersion: v1
kind: Secret
metadata:
  name: bookstack-secret
  namespace: bookstack
type: Opaque

stringData:
  APP_KEY: "base64:LUZTPFPYD34IT00EmLGk9LLvHIJLvkLU4WuLJ9iWgCc="
  DB_DATABASE: "bookstackapp"
  DB_USERNAME: "bookstack"
  DB_PASSWORD: "bookstackpass"
  MARIADB_ROOT_PASSWORD: "rootpass"
  APP_URL: "http://127.0.0.1:8086"